kind: ConfigMap
apiVersion: v1
metadata:
  name: photo-album-configmap
  namespace: default
data:
  DB_NAME: photo_db
  MONGO_SERVER: mongodb://<APP_NAME>.<NAMESPACE>.svc.cluster.local:27017   #Example mongodb://mongo.default.svc.cluster.local:27017
---
apiVersion: v1
kind: Service
metadata:
  name: photo-album
  namespace: default
  labels:
    app: photo
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: photo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-album
  namespace: default
  labels:
    app: photo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo
  template:
    metadata:
      labels:
        app: photo
    spec:
      containers:
      - name: photo-album
        image: chrisjen83/photo_album-arch:v4
        imagePullPolicy: Always
        env:
          - name: "ecs_endpoint_url"
            valueFrom:
              secretKeyRef:
                name: yaml-instance-v2-binding
                key: endpoint
          - name: "ecs_access_key_id"
            valueFrom:
              secretKeyRef:
                name: yaml-instance-v2-binding
                key: accessKey
          - name: "ecs_secret_key"
            valueFrom:
              secretKeyRef:
                name: yaml-instance-v2-binding
                key: secretKey
          - name: "ecs_bucket_name"
            valueFrom:
              secretKeyRef:
                name: yaml-instance-v2-binding
                key: bucket
        ports:
        - containerPort: 5000
